[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
# TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[font]
size = 10.5
# size = 12.0
normal = { family = "JetBrainsMono Nerd Font", style = "medium" }
# normal = { family = "Maple Mono NF", style = "normal" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[terminal.shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
opacity = 1
decorations = "full"
blur = false
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
padding = { x = 3, y = 3 }
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 180
lines = 45
