git:
  paging:
    colorArg: always
    pager: delta --diff-so-fancy --dark --paging=never --syntax-theme=Catppuccin-mocha
    # pager: diff-so-fancy
    # externalDiffCommand: difft --color=always --display=inline
    # externalDiffCommand: difft --color=always --display=inline
gui:
  theme:
    # lightTheme: false
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
