palette = "catppuccin_mocha"

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$ssh_symbol\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$memory_usage\
$docker_context\
$c\
$cpp\
$python\
$conda\
$cmake\
$rust\
$lua\
$cmd_duration\
$line_break$character"""

[fill]
symbol = ' '

[character]
disabled = false
success_symbol = '[[󰄛 ](green)](bold fg:peach)'
error_symbol = '[[󰄛 ](red)](bold fg:peach)'
vimcmd_symbol = '[󰄛 ](subtext1)'
vimcmd_replace_one_symbol = '[󰄛 ](bold fg:purple)'
vimcmd_replace_symbol = '[󰄛 ](bold fg:purple)'
vimcmd_visual_symbol = '[󰄛 ](bold fg:lavender)'

[line_break]
disabled = false

[os]
disabled = false
style = 'bold blue'

[username]
style_user = 'bold green'
format = ' [$user]($style) '
disabled = true
show_always = true

[directory]
truncation_symbol = '…/'
format = "[ $path ]($style)"
read_only = " 󰌾"
truncation_length = 2
style = "bold lavender"

[directory.substitutions]
"Home" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[hostname]
ssh_only = false
style = 'bold sapphire'
format = "[$ssh_symbol$hostname]($style) "
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false
ssh_symbol = " "

[cmd_duration]
min_time = 20_000                    # milliseconds
format = 'took [$duration]($style) '
style = 'bold peach'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = "󰔷 "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[git_branch]
style = 'bold mauve'
format = 'on [$symbol$branch(:$remote_branch)]($style) '
symbol = " "

[git_commit]
tag_symbol = '  '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold mauve'
ahead = '${count}'
diverged = '⇕${ahead_count}${behind_count}'
behind = '${count}'
disabled = false

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = true

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[memory_usage]
format = '$symbol [${ram}( | ${swap})]($style) '
threshold = 75                                   # usage percentage
symbol = "󰍛 "
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
detect_extensions = ["py", "ipynb", "model"]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
